# Database URL (auth_db သည် သင် ခုနက ဆောက်လိုက်တဲ့ နာမည်)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-db
spring.datasource.username=postgres
spring.datasource.password=123456

# Database settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=aB3#kL9@zXv5nN2!qW8$rT7^mP4&jY1*some-long-random-string-must-be-32-chars
